CREATE
  TABLE ACCOUNT
  (
    ID              integer NOT NULL ,
    ACCOUNT_NUMBER  VARCHAR (50) NOT NULL ,
    BIC             VARCHAR (9) NOT NULL ,
    AMOUNT          NUMERIC (17,2) NOT NULL
  );

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID);